### ISSUE TITLE
[기능] 로그인 처리 관련

### ISSUE THREAD

**Issue by cjw9506** [Fitness-Commerce/backend#1]
## 이슈 설명
로그인 관련 이슈입니다.
기존 로그인 요청을 서버에서 처리하여 클라이언트로 응답을 보내는 과정에서 accessToken과 refreshToken을 둘 다 String으로 보내려 하였으나, accessToken만 String으로 응답을 보내고, refreshToken은 Set-Cookie 헤더에 포함하여 보내는 방법을 구현하려고 합니다.

## 원하는 결과
프론트의 원활한 진행.

## 스크린샷 (선택사항)
가능하면 이슈를 설명하는 데 도움이 되는 스크린샷을 첨부해주세요.

## 기타
코멘트가 있다면 얘기해주세요.

**Comment by wdgWon** [comment]
이건 로그인 응답을 받아봐야 감이 잡힐것 같아요
저 Set-Cookie라는게 refreshToken을 직접 쿠키에 넣는 거라면
accessToken에도 적용했을때 어떤 문제가 있나요?
